apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-todo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: django-todo
  template:
    metadata:
      labels:
        app: django-todo
    spec:
      containers:
      - name: django-todo
        image: shameem2001/django-todo-app:v2.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: django-todo
  # annotations:
  #   service.beta.kubernetes.io/aws-load-balancer-name: a41b99b5feebd4f5a934efd4714d063d-703219868.us-east-1.elb.amazonaws.com
spec:
  selector:
    app: django-todo
  # type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8000


